enable_button: 5 # Left trigger button
angular_button: 5 # Right trigger button

axis_linear:
  x: 0
  y: 1
  z: 3

scale_linear:
  x: 5.005
  y: -5.005
  z: 5.005
  
axis_angular:
  x: 7
  y: 2
  z: 6
  
scale_angular:
  x: -1.05
  y: 1.05
  z: 1.05
